services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./nginx/cert.crt:/etc/ssl/certs/cert.crt:ro
      # - ./nginx/cert.key:/etc/ssl/private/cert.key:ro
    depends_on:
      - api
    restart: always
